server:
  port: "8081"
management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
      base-path: "/private"
      path-mapping:
        prometheus: "metrics"
  metrics:
    export:
      prometheus:
        enabled: true