server:
  port: "8081"
downstreams:
  urls:
    -
      url: "http://localhost:8083"
    -
      url: "http://localhost:8082"
management:
  endpoints:
    web:
      exposure:
        include: "prometheus, info"
      base-path: "/private"
      path-mapping:
        prometheus: "metrics"
  metrics:
    export:
      prometheus:
        enabled: true
  info:
    env:
      enabled: true
info:
  app:
    name: "Pet Project Purchase Service"
    description: "Purchase Service Microservice that communicates with Order Service and Inventory Service"
    java:
      source: ${sourceCompatibility}
      target: ${sourceCompatibility}